### ISSUE TITLE
Make npm release

### ISSUE THREAD

**Issue by Kagami** [rfk/wasm-polyfill#2]
Hi. Could you please publish `wasm-polyfill.min.js` to NPM? I would like to try it as polyfill for my simple WebAssembly-powered library.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
